import { FieldValue } from "@google-cloud/firestore";
import { NextResponse } from "next/server";
import { z } from "zod";
import { verifyInventoryAccess } from "@/lib/firebase-admin";
import { firestoreClient } from "@/lib/firestore";
import { apiError,jsonBody } from "@/lib/inventory/api";
import { writeAudit,serialize } from "@/lib/inventory/service";
const schema=z.object({transferId:z.string().min(2),transporterId:z.string().min(2),vehicleNumber:z.string().min(2),vehicleType:z.string().min(1),payloadCapacity:z.number().nonnegative(),driverName:z.string().min(2),driverPhone:z.string().regex(/^\+?[0-9]{10,15}$/),originLocationId:z.string().min(2),destinationLocationId:z.string().min(2),routeDistanceKm:z.number().nonnegative(),plannedDispatchDate:z.string().date(),expectedArrivalDate:z.string().date(),freightAmount:z.number().nonnegative(),tollCharges:z.number().nonnegative(),loadingCharges:z.number().nonnegative(),unloadingCharges:z.number().nonnegative(),insuranceAmount:z.number().nonnegative(),taxAmount:z.number().nonnegative(),otherCharges:z.number().nonnegative().default(0),transportBillUrl:z.string().url().nullish(),proofOfDeliveryUrl:z.string().url().nullish(),status:z.enum(["PLANNED","DISPATCHED","IN_TRANSIT","DELIVERED","CANCELLED"]).default("PLANNED")});
export async function GET(request:Request){try{const actor=await verifyInventoryAccess(request,["admin","logistics_manager","warehouse_manager","branch_store_manager","finance_analyst"]);const s=await firestoreClient().collection("outbound_dispatches").orderBy("created_at","desc").limit(300).get();return NextResponse.json({dispatches:s.docs.map(serialize).filter((x)=>actor.isAdmin||actor.locationIds.includes(String(x.origin_location_id))||actor.locationIds.includes(String(x.destination_location_id)))});}catch(e){return apiError(e)}}
export async function POST(request:Request){try{const p=schema.parse(await jsonBody(request));const actor=await verifyInventoryAccess(request,["admin","logistics_manager"],p.originLocationId);const total=p.freightAmount+p.tollCharges+p.loadingCharges+p.unloadingCharges+p.insuranceAmount+p.taxAmount+p.otherCharges;const ref=firestoreClient().collection("outbound_dispatches").doc();const record={dispatch_id:ref.id,transfer_id:p.transferId,transporter_id:p.transporterId,vehicle_number:p.vehicleNumber,vehicle_type:p.vehicleType,payload_capacity:p.payloadCapacity,driver_name:p.driverName,driver_phone:p.driverPhone,origin_location_id:p.originLocationId,destination_location_id:p.destinationLocationId,route_distance_km:p.routeDistanceKm,planned_dispatch_date:p.plannedDispatchDate,expected_arrival_date:p.expectedArrivalDate,freight_amount:p.freightAmount,toll_charges:p.tollCharges,loading_charges:p.loadingCharges,unloading_charges:p.unloadingCharges,insurance_amount:p.insuranceAmount,tax_amount:p.taxAmount,other_charges:p.otherCharges,total_transport_cost:total,transport_bill_url:p.transportBillUrl||null,proof_of_delivery_url:p.proofOfDeliveryUrl||null,status:p.status,created_by:actor.uid,created_at:FieldValue.serverTimestamp(),updated_at:FieldValue.serverTimestamp()};await ref.create(record);await writeAudit(actor.uid,"dispatch.create","outbound_dispatch",ref.id,null,record);return NextResponse.json({dispatchId:ref.id,totalTransportCost:total},{status:201});}catch(e){return apiError(e)}}
