import { describe, expect, it } from "vitest";
import { createManualEntity, registrationEntityFields } from "@/lib/entity-locator/api";
import { LocationEntitySearchService } from "@/lib/entity-locator/entity-search-service";
import { deduplicateEntities, normalizeEntityCandidate, rankEntities } from "@/lib/entity-locator/normalization";
import type { EntityAnalytics, EntityDirectoryRepository, EntityType, LocationEntityResult, LocationEntitySearchProvider } from "@/lib/entity-locator/types";

const base = { cityCode: "CHENNAI" as const, zoneCode: "CHENNAI_WEST" as const, query: "dlf", limit: 10 };
function entity(entityType: EntityType, id: string, overrides: Partial<LocationEntityResult> = {}): LocationEntityResult {
  const office = entityType === "office";
  return { id, entity_type: entityType, display_name: office ? "DLF IT Park" : "Tata Consultancy Services", normalized_name: office ? "dlf it park" : "tata consultancy services", formatted_address: "Ramapuram, Chennai, Tamil Nadu 600089", locality: "Ramapuram", sub_locality: null, zone_code: "CHENNAI_WEST", zone_name: "West Chennai", city_code: "CHENNAI", city_name: "Chennai", state: "Tamil Nadu", postal_code: "600089", latitude: 13.02, longitude: 80.17, provider: "google", provider_place_id: id, category: office ? "corporate_office" : "company", verification_status: "likely", confidence: 0.95, is_active: true, search_keywords: [office ? "dlf" : "tat"], ...overrides };
}
function setup(options: { local?: LocationEntityResult[]; cached?: LocationEntityResult[]; google?: LocationEntityResult[] | Error; serpapi?: LocationEntityResult[] | Error; analyticsFailure?: boolean } = {}) {
  let googleCalls = 0; let serpCalls = 0;
  const repository: EntityDirectoryRepository = { search: async () => options.local || [], getByIds: async () => [], getById: async () => null, saveMany: async () => undefined, getCached: async () => options.cached ? { entities: options.cached, providerUsed: "google" } : null, setCached: async () => undefined };
  const provider = (name: "google" | "serpapi", result?: LocationEntityResult[] | Error): LocationEntitySearchProvider => ({ name, search: async () => { if (name === "google") googleCalls += 1; else serpCalls += 1; if (result instanceof Error) throw result; return result || []; } });
  const analytic = async () => { if (options.analyticsFailure) throw new Error("BigQuery unavailable"); };
  const analytics: EntityAnalytics = { recordSearch: analytic, recordEntities: analytic, recordRegistration: analytic, recordProviderUsage: analytic };
  return { service: new LocationEntitySearchService({ repository, google: provider("google", options.google), serpapi: provider("serpapi", options.serpapi), analytics, defer: (task) => { void task(); } }), calls: () => ({ google: googleCalls, serpapi: serpCalls }) };
}

describe("LocationEntitySearchService", () => {
  it("does not call providers for a two-character office query", () => { const { service, calls } = setup(); expect(() => service.search({ ...base, entityType: "office", query: "dl" })).toThrow(/three characters/i); expect(calls()).toEqual({ google: 0, serpapi: 0 }); });
  it("searches offices at three characters", async () => { const { service, calls } = setup({ google: [entity("office", "office-1")] }); const response = await service.search({ ...base, entityType: "office" }); expect(response.results[0].display_name).toBe("DLF IT Park"); expect(calls().google).toBe(1); });
  it("filters Bangalore offices from a Chennai search", async () => { const wrong = entity("office", "wrong", { city_code: "COIMBATORE", city_name: "Coimbatore", zone_code: "COIMBATORE_EAST", zone_name: "East Coimbatore" }); const { service } = setup({ google: [wrong] }); expect((await service.search({ ...base, entityType: "office" })).results).toHaveLength(0); });
  it("uses cached Firestore entities without provider calls", async () => { const { service, calls } = setup({ cached: [entity("office", "cached")] }); const response = await service.search({ ...base, entityType: "office" }); expect(response.meta.cache_hit).toBe(true); expect(calls()).toEqual({ google: 0, serpapi: 0 }); });
  it("uses SerpAPI if Google fails", async () => { const { service } = setup({ google: new Error("offline"), serpapi: [entity("office", "serp", { provider: "serpapi" })] }); expect((await service.search({ ...base, entityType: "office" })).results[0].provider).toBe("serpapi"); });
  it("searches and normalizes companies", async () => { const tata = entity("company", "tata"); const { service } = setup({ google: [tata] }); const response = await service.search({ ...base, entityType: "company", query: "tat" }); expect(response.results[0]).toMatchObject({ entity_type: "company", display_name: "Tata Consultancy Services" }); });
  it("deduplicates Google and SerpAPI representations", () => { const google = entity("company", "same"); const serp = entity("company", "copy", { provider: "serpapi", provider_place_id: "same" }); expect(deduplicateEntities([google, serp])).toHaveLength(1); });
  it("keeps search working when analytics fails", async () => { const { service } = setup({ google: [entity("office", "office-1")], analyticsFailure: true }); await expect(service.search({ ...base, entityType: "office" })).resolves.toMatchObject({ meta: { count: 1 } }); });
});

describe("entity profiles and manual fallback", () => {
  it("excludes schools from office results", () => { expect(normalizeEntityCandidate({ entityType: "office", name: "DLF Public School", address: "Porur, Chennai", latitude: 13, longitude: 80, provider: "google", types: ["school"], selectedCityCode: "CHENNAI", selectedZoneCode: "CHENNAI_WEST" })).toBeNull(); });
  it("excludes dance studios from company results", () => { expect(normalizeEntityCandidate({ entityType: "company", name: "Tat Dance Studio", address: "Virugambakkam, Chennai", latitude: 13, longitude: 80, provider: "google", types: ["association_or_organization"], selectedCityCode: "CHENNAI", selectedZoneCode: "CHENNAI_WEST" })).toBeNull(); });
  it("ranks a corporate company above a generic matching business", () => { const generic = entity("company", "generic", { display_name: "TAT", normalized_name: "tat", category: "travel_agency" }); const corporate = entity("company", "corporate", { category: "corporate_office" }); expect(rankEntities([generic, corporate], "tat", "CHENNAI_WEST")[0].id).toBe("corporate"); });
  it("resolves office locality through shared zones", () => { const result = normalizeEntityCandidate({ entityType: "office", name: "DLF Corporate Office", address: "Ramapuram, Chennai, Tamil Nadu 600089", locality: "Ramapuram", latitude: 13, longitude: 80, provider: "google", types: ["corporate_office"], selectedCityCode: "CHENNAI", selectedZoneCode: "CHENNAI_WEST" }); expect(result?.zone_code).toBe("CHENNAI_WEST"); });
  it("creates an unverified manual company with separate company identity", () => { const result = createManualEntity("company", { display_name: "Acme Technologies Pvt Ltd", formatted_address: "Porur, Chennai, Tamil Nadu", locality: "Porur", postal_code: "600116", city_code: "CHENNAI", zone_code: "CHENNAI_WEST" }); expect(result.entity).toMatchObject({ entity_type: "company", provider: "manual", verification_status: "unverified", latitude: null, longitude: null }); });
  it("normalizes a college with the shared city and zone resolver", () => { const result = normalizeEntityCandidate({ entityType: "college", name: "Chennai Engineering College", address: "Porur, Chennai, Tamil Nadu 600116", locality: "Porur", latitude: 13.03, longitude: 80.15, provider: "google", types: ["college"], selectedCityCode: "CHENNAI", selectedZoneCode: "CHENNAI_WEST" }); expect(result).toMatchObject({ entity_type: "college", zone_code: "CHENNAI_WEST", category: "college" }); });
  it("excludes schools from college results", () => { expect(normalizeEntityCandidate({ entityType: "college", name: "Chennai Public School", address: "Porur, Chennai", latitude: 13, longitude: 80, provider: "google", types: ["school"], selectedCityCode: "CHENNAI", selectedZoneCode: "CHENNAI_WEST" })).toBeNull(); });
  it("creates an unverified manual college", () => { const result = createManualEntity("college", { display_name: "LunchBox Arts and Science College", formatted_address: "Porur, Chennai, Tamil Nadu", locality: "Porur", postal_code: "600116", city_code: "CHENNAI", zone_code: "CHENNAI_WEST" }); expect(result.entity).toMatchObject({ entity_type: "college", provider: "manual", verification_status: "unverified" }); });
  it("copies authoritative latitude and longitude into registration data", () => { expect(registrationEntityFields(entity("office", "office-location"))).toMatchObject({ office_id: "office-location", latitude: 13.02, longitude: 80.17 }); });
});
