import { FieldValue } from "@google-cloud/firestore";
import { NextResponse } from "next/server";
import { verifyInventoryAccess } from "@/lib/firebase-admin";
import { firestoreClient } from "@/lib/firestore";
import { apiError, jsonBody } from "@/lib/inventory/api";
import { supplierRateSchema } from "@/lib/inventory/domain";
import { serialize, writeAudit } from "@/lib/inventory/service";
export async function GET(request: Request) { try { await verifyInventoryAccess(request, ["admin", "procurement_manager", "finance_analyst", "planning_manager"]); const snapshot = await firestoreClient().collection("supplier_item_rates").orderBy("effective_from", "desc").limit(500).get(); return NextResponse.json({ rates: snapshot.docs.map(serialize) }); } catch (error) { return apiError(error); } }
export async function POST(request: Request) { try { const actor = await verifyInventoryAccess(request, ["admin", "procurement_manager"]); const parsed = supplierRateSchema.parse(await jsonBody(request)); const db = firestoreClient(); const ref = parsed.rateId ? db.collection("supplier_item_rates").doc(parsed.rateId) : db.collection("supplier_item_rates").doc(); const previous = await db.collection("supplier_item_rates").where("supplier_id", "==", parsed.supplierId).where("item_id", "==", parsed.itemId).where("status", "==", "ACTIVE").limit(1).get(); const oldRate = previous.empty ? null : Number(previous.docs[0].get("rate")); const variancePercent = oldRate ? (parsed.rate - oldRate) / oldRate * 100 : 0; const record = { rate_id: ref.id, supplier_id: parsed.supplierId, item_id: parsed.itemId, unit: parsed.unit, rate: parsed.rate, currency: parsed.currency, price_source: parsed.priceSource, source_reference_id: parsed.sourceReferenceId || null, fetched_at: parsed.priceSource === "MANUAL" ? null : FieldValue.serverTimestamp(), effective_from: parsed.effectiveFrom, effective_to: parsed.effectiveTo || null, minimum_order_quantity: parsed.minimumOrderQuantity, lead_time_days: parsed.leadTimeDays, status: parsed.status, version: 1, created_by: actor.uid, created_at: FieldValue.serverTimestamp(), updated_at: FieldValue.serverTimestamp() }; const batch = db.batch(); batch.create(ref, record); const history = db.collection("purchase_cost_history").doc(); batch.create(history, { history_id: history.id, supplier_id: parsed.supplierId, item_id: parsed.itemId, old_rate: oldRate, new_rate: parsed.rate, variance_amount: oldRate === null ? 0 : parsed.rate - oldRate, variance_percent: variancePercent, effective_date: parsed.effectiveFrom, price_source: parsed.priceSource, recorded_by: actor.uid, recorded_at: FieldValue.serverTimestamp() }); await batch.commit(); await writeAudit(actor.uid, "supplier_rate.create", "supplier_item_rate", ref.id, null, record, { variancePercent }); return NextResponse.json({ rateId: ref.id, variancePercent, status: parsed.status }, { status: 201 }); } catch (error) { return apiError(error); } }
