"use client";
/* eslint-disable @typescript-eslint/no-explicit-any -- Google Maps SDK is loaded dynamically. */
import { useEffect, useRef, useState } from "react";
import type { Franchise } from "@/lib/franchises";
declare global { interface Window { google?: any; } }
type School = { name: string; address: string; position: { lat: number; lng: number } };

export default function ChennaiFranchiseMapDrawer({ open, onClose, franchises }: { open: boolean; onClose: () => void; franchises: Franchise[] }) {
  const mapNode = useRef<HTMLDivElement>(null); const [selected, setSelected] = useState<Franchise | null>(null); const [schools, setSchools] = useState<School[]>([]); const [mapError, setMapError] = useState("");
  useEffect(() => { if (!open) return; const previous = document.activeElement as HTMLElement | null; const closeOnEscape = (event: KeyboardEvent) => event.key === "Escape" && onClose(); document.addEventListener("keydown", closeOnEscape); document.body.style.overflow = "hidden"; return () => { document.removeEventListener("keydown", closeOnEscape); document.body.style.overflow = ""; previous?.focus(); }; }, [open, onClose]);
  useEffect(() => { if (!open || !mapNode.current) return; let cancelled = false; (async () => { try { const { key } = await (await fetch("/api/maps/config")).json(); if (!key) throw new Error("Google Maps is not configured."); if (!window.google) await new Promise<void>((resolve, reject) => { const script = document.createElement("script"); script.src = `https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(key)}&libraries=places`; script.async = true; script.onload = () => resolve(); script.onerror = () => reject(new Error("Google Maps failed to load.")); document.head.append(script); }); if (cancelled || !mapNode.current) return; const map = new window.google.maps.Map(mapNode.current, { center: { lat: 13.0827, lng: 80.2707 }, zoom: 10, mapTypeControl: false, fullscreenControl: true }); const info = new window.google.maps.InfoWindow(); const places = new window.google.maps.places.PlacesService(map); franchises.filter((item) => item.location).forEach((franchise) => { const marker = new window.google.maps.Marker({ map, position: franchise.location, title: franchise.name }); marker.addListener("click", () => { setSelected(franchise); setSchools([]); info.setContent(`<strong>${franchise.name}</strong><br/>${franchise.area}, Chennai<br/>${franchise.category}`); info.open({ map, anchor: marker }); places.nearbySearch({ location: franchise.location, radius: 3000, type: "school" }, (results: any[], status: string) => { if (status === window.google.maps.places.PlacesServiceStatus.OK) setSchools((results || []).slice(0, 12).map((school) => ({ name: school.name, address: school.vicinity || "Chennai", position: { lat: school.geometry.location.lat(), lng: school.geometry.location.lng() } }))); }); }); }); } catch (error) { setMapError(error instanceof Error ? error.message : "Unable to load Google Maps."); } })(); return () => { cancelled = true; }; }, [open, franchises]);
  if (!open) return null; return <div className="franchise-map-overlay" role="dialog" aria-modal="true" aria-labelledby="chennai-map-title"><aside className="franchise-map-drawer"><header><div><h2 id="chennai-map-title">Chennai Franchise Network</h2><p>Explore LunchBox franchise partners and service coverage.</p></div><button onClick={onClose} aria-label="Close Chennai map">×</button></header><div className="franchise-map-body"><div className="franchise-google-map" ref={mapNode}>{mapError && <p role="alert">{mapError}</p>}</div><div className="franchise-map-sidebar">{selected ? <><b>{selected.name}</b><p>{selected.companyName}</p><p>{selected.area} · {selected.category}</p><h3>Nearby schools</h3>{schools.length ? <ul>{schools.map((school) => <li key={`${school.name}-${school.address}`}>{school.name}<small>{school.address}</small></li>)}</ul> : <p>Loading nearby schools…</p>}</> : <><b>{franchises.filter((item) => item.location).length} mapped franchises</b><p>Zoom and pan to explore available franchise locations. Select a marker to analyse nearby schools.</p></>}</div></div></aside></div>;
}
