import { createHash } from "node:crypto";
import { BigQuery } from "@google-cloud/bigquery";
import { FieldValue } from "@google-cloud/firestore";
import { Storage } from "@google-cloud/storage";
import { firestoreClient } from "@/lib/firestore";
import { forecastReplenishment } from "@/lib/inventory/domain";

export function verifyJobSecret(request: Request) { const expected = process.env.INVENTORY_JOB_SECRET; const supplied = request.headers.get("X-Inventory-Job-Secret"); if (!expected || supplied !== expected) throw new Error("Inventory job authentication failed."); }

export async function syncPriceFeed(actorId = "system:price-feed") {
  const endpoint = process.env.INVENTORY_PRICE_FEED_URL; const apiKey = process.env.INVENTORY_PRICE_FEED_API_KEY; if (!endpoint) throw new Error("INVENTORY_PRICE_FEED_URL is not configured.");
  const requestedAt = new Date(); const response = await fetch(endpoint, { headers: apiKey ? { Authorization: `Bearer ${apiKey}` } : {} }); const raw = await response.text(); if (!response.ok) throw new Error(`Price feed returned HTTP ${response.status}.`); const parsed = JSON.parse(raw) as { rates?: Array<{ itemId: string; supplierId?: string; unit: string; rate: number; currency: string; sourceReferenceId?: string }> }; if (!Array.isArray(parsed.rates)) throw new Error("Price feed response does not contain rates.");
  const bucketName = process.env.INVENTORY_DOCUMENTS_BUCKET || process.env.GCS_BUCKET; let payloadUri: string | null = null; if (bucketName) { const name = `inventory-price-feeds/${requestedAt.toISOString().slice(0,10)}/${crypto.randomUUID()}.json`; await new Storage({ projectId: process.env.GCP_PROJECT_ID }).bucket(bucketName).file(name).save(raw, { contentType: "application/json", resumable: false }); payloadUri = `gs://${bucketName}/${name}`; }
  const db=firestoreClient();const batch=db.batch();const ids:string[]=[];for(const rate of parsed.rates){if(!rate.itemId||!rate.unit||!Number.isFinite(rate.rate)||rate.rate<0)continue;const ref=db.collection("online_price_feed_log").doc();ids.push(ref.id);batch.create(ref,{feed_log_id:ref.id,item_id:rate.itemId,supplier_id:rate.supplierId||null,feed_provider:new URL(endpoint).hostname,requested_at:requestedAt.toISOString(),responded_at:new Date().toISOString(),raw_response_payload_uri:payloadUri,raw_response_sha256:createHash("sha256").update(raw).digest("hex"),parsed_rate:rate.rate,unit:rate.unit,currency:rate.currency,source_reference_id:rate.sourceReferenceId||null,applied:false,applied_by:null,status:"PENDING_APPROVAL",created_by:actorId,created_at:FieldValue.serverTimestamp()});}await batch.commit();return{feedRecords:ids.length,payloadUri};
}

export async function runForecast(locationId:string,method="MOVING_AVERAGE",lookbackDays=30,actorId="system:forecast"){
  const db=firestoreClient();const cutoff=new Date(Date.now()-lookbackDays*86_400_000);const [balances,transactions]=await Promise.all([db.collection("inventory_balances").where("location_id","==",locationId).get(),db.collection("stock_transactions").where("location_id","==",locationId).where("performed_at",">=",cutoff).get()]);const run=db.collection("forecast_runs").doc();const batch=db.batch();batch.create(run,{forecast_run_id:run.id,location_id:locationId,forecast_date:new Date().toISOString().slice(0,10),forecast_period_days:lookbackDays,method,generated_by:actorId,status:"COMPLETED",created_at:FieldValue.serverTimestamp()});for(const balance of balances.docs){const itemId=String(balance.get("item_id"));const consumption=transactions.docs.filter((tx)=>tx.get("item_id")===itemId&&["ISSUE","WASTAGE"].includes(String(tx.get("transaction_type")))).reduce((sum,tx)=>sum+Number(tx.get("quantity")||0),0);const average=consumption/lookbackDays;const available=Number(balance.get("available_stock")||0);const inTransit=Number(balance.get("in_transit_stock")||0);const result=forecastReplenishment({availableStock:available,inTransitStock:inTransit,averageDailyConsumption:average,maximumDailyConsumption:average*1.25,averageLeadTimeDays:Number(balance.get("average_lead_time_days")||7),maximumLeadTimeDays:Number(balance.get("maximum_lead_time_days")||10),targetStock:Number(balance.get("maximum_stock")||balance.get("threshold_base_quantity")||available),asOf:new Date()});const ref=db.collection("forecast_items").doc(`${run.id}_${locationId}_${itemId}`);batch.set(ref,{forecast_item_id:ref.id,forecast_run_id:run.id,item_id:itemId,location_id:locationId,average_daily_consumption:average,forecasted_demand:average*lookbackDays,current_stock:Number(balance.get("current_stock")||0),in_transit_stock:inTransit,safety_stock:result.safetyStock,reorder_point:result.reorderPoint,forecasted_depletion_date:result.forecastedDepletionDate,recommended_reorder_quantity:result.recommendedQuantity,recommended_transfer_quantity:result.recommendedQuantity,alert_color:balance.get("alert_color")||"GREEN",created_at:FieldValue.serverTimestamp()});}await batch.commit();return{forecastRunId:run.id,itemCount:balances.size};
}

export async function processAlertNotifications(){const db=firestoreClient();const alerts=await db.collection("inventory_alerts").where("status","in",["OPEN","ESCALATED"]).limit(500).get();const batch=db.batch();let count=0;for(const alert of alerts.docs){for(const role of (alert.get("notify_roles")||[]) as string[]){const id=`${alert.id}_${role}_IN_APP`;const ref=db.collection("alert_notifications").doc(id);batch.set(ref,{notification_id:id,alert_id:alert.id,recipient_role:role,recipient_user_id:null,channel:"IN_APP",delivery_status:"PENDING",created_at:FieldValue.serverTimestamp()},{merge:true});count++;}const triggered=alert.get("triggered_at")?.toDate?.() as Date|undefined;const delay=Number(alert.get("escalation_delay_minutes")||30);if(triggered&&Date.now()-triggered.getTime()>delay*60_000&&alert.get("status")==="OPEN")batch.update(alert.ref,{status:"ESCALATED",escalated_at:FieldValue.serverTimestamp(),updated_at:FieldValue.serverTimestamp()});}await batch.commit();return{alerts:alerts.size,notificationsQueued:count};}

export async function exportInventoryAnalytics(){const projectId=process.env.GCP_PROJECT_ID;const dataset=process.env.INVENTORY_BIGQUERY_DATASET||"inventory_analytics";if(!projectId)throw new Error("GCP_PROJECT_ID is required.");const db=firestoreClient();const bq=new BigQuery({projectId});const [transactions,alerts]=await Promise.all([db.collection("stock_transactions").where("analytics_exported","!=",true).limit(500).get(),db.collection("inventory_alerts").where("analytics_exported","!=",true).limit(500).get()]);if(!transactions.empty)await bq.dataset(dataset).table("bq_stock_transactions").insert(transactions.docs.map((d)=>({transaction_id:d.id,transaction_type:d.get("transaction_type"),item_id:d.get("item_id"),location_id:d.get("location_id"),source_location_id:d.get("source_location_id")||null,destination_location_id:d.get("destination_location_id")||null,quantity:d.get("quantity"),unit:d.get("unit"),cost_per_unit:d.get("cost_per_unit")||0,landed_cost_per_unit:d.get("landed_cost_per_unit")||0,total_cost:d.get("total_cost")||0,reference_id:d.get("reference_id")||null,reference_type:d.get("reference_type")||null,batch_number:d.get("batch_number")||null,expiry_date:d.get("expiry_date")||null,performed_by:d.get("performed_by"),performed_at:d.get("performed_at")?.toDate?.()?.toISOString(),exported_at:new Date().toISOString()})),{raw:true});if(!alerts.empty)await bq.dataset(dataset).table("bq_alerts").insert(alerts.docs.map((d)=>({alert_id:d.id,alert_type:d.get("alert_type"),severity:d.get("severity"),item_id:d.get("item_id")||null,location_id:d.get("location_id")||null,trigger_value:d.get("trigger_value")||0,threshold_value:d.get("threshold_value")||0,status:d.get("status"),triggered_at:d.get("triggered_at")?.toDate?.()?.toISOString(),resolved_at:d.get("resolved_at")?.toDate?.()?.toISOString()||null,exported_at:new Date().toISOString()})),{raw:true});const batch=db.batch();transactions.docs.forEach((d)=>batch.update(d.ref,{analytics_exported:true,analytics_exported_at:FieldValue.serverTimestamp()}));alerts.docs.forEach((d)=>batch.update(d.ref,{analytics_exported:true,analytics_exported_at:FieldValue.serverTimestamp()}));await batch.commit();return{transactions:transactions.size,alerts:alerts.size};}
