import { FieldValue } from "@google-cloud/firestore";
import { firestoreClient } from "@/lib/firestore";
import { goodsReceiptSchema, purchaseOrderSchema } from "@/lib/inventory/domain";
import { writeAudit } from "@/lib/inventory/service";

const key = (...parts: string[]) => parts.map((part) => part.replace(/[^A-Za-z0-9_-]/g, "_")).join("_");
const number = (value: unknown) => Number.isFinite(Number(value)) ? Number(value) : 0;

export async function createPurchaseOrder(input: unknown, actorId: string) {
  const parsed = purchaseOrderSchema.parse(input); const db = firestoreClient(); const ref = parsed.poId ? db.collection("purchase_orders").doc(parsed.poId) : db.collection("purchase_orders").doc();
  const lines = parsed.items.map((item) => ({ item_id: item.itemId, ordered_quantity: item.quantity, received_quantity: 0, unit: item.unit, unit_rate: item.unitRate, supplier_rate_id: item.supplierRateId, tax_percent: item.taxPercent, line_material_cost: item.quantity * item.unitRate, line_tax: item.quantity * item.unitRate * item.taxPercent / 100 }));
  const material = lines.reduce((sum, line) => sum + line.line_material_cost, 0); const tax = lines.reduce((sum, line) => sum + line.line_tax, 0);
  const record = { po_id: ref.id, po_number: `PO-${Date.now()}-${ref.id.slice(0, 5).toUpperCase()}`, supplier_id: parsed.supplierId, destination_location_id: parsed.destinationLocationId, currency: parsed.currency, expected_delivery_date: parsed.expectedDeliveryDate, estimated_material_cost: material, estimated_tax: tax, estimated_inbound_freight: parsed.estimatedInboundFreight, estimated_landed_cost: material + tax + parsed.estimatedInboundFreight, allocation_basis: parsed.allocationBasis, items: lines, status: "DRAFT", requested_by: actorId, approved_by: null, remarks: parsed.remarks, created_at: FieldValue.serverTimestamp(), updated_at: FieldValue.serverTimestamp() };
  await ref.create(record); await writeAudit(actorId, "po.create", "purchase_order", ref.id, null, record); return { poId: ref.id, poNumber: record.po_number, status: record.status, estimatedLandedCost: record.estimated_landed_cost };
}

export async function approvePurchaseOrder(poId: string, actorId: string) {
  const db = firestoreClient(); const ref = db.collection("purchase_orders").doc(poId); const before = await ref.get(); if (!before.exists) throw new Error("Purchase order does not exist."); if (before.get("status") !== "DRAFT" && before.get("status") !== "SUBMITTED") throw new Error("Only draft or submitted purchase orders can be approved."); if (before.get("requested_by") === actorId) throw new Error("The purchase order requester cannot approve the same order.");
  const after = { status: "APPROVED", approved_by: actorId, approved_at: FieldValue.serverTimestamp(), updated_at: FieldValue.serverTimestamp() }; await ref.update(after); await writeAudit(actorId, "po.approve", "purchase_order", poId, before.data(), after); return { poId, status: "APPROVED" };
}

export async function receiveGoods(input: unknown, actorId: string) {
  const parsed = goodsReceiptSchema.parse(input); const db = firestoreClient(); const grnRef = parsed.grnId ? db.collection("goods_receipts").doc(parsed.grnId) : db.collection("goods_receipts").doc(); const poRef = db.collection("purchase_orders").doc(parsed.poId);
  const result = await db.runTransaction(async (transaction) => {
    const po = await transaction.get(poRef); if (!po.exists) throw new Error("Purchase order does not exist."); if (!["APPROVED", "PARTIALLY_RECEIVED"].includes(String(po.get("status")))) throw new Error("Purchase order is not open for receipt."); if (po.get("destination_location_id") !== parsed.locationId) throw new Error("GRN location does not match the purchase order destination.");
    const accepted = parsed.items.filter((item) => item.acceptedQuantity > 0); const totalBasis = accepted.reduce((sum, item) => sum + (parsed.allocationBasis === "VALUE" ? item.acceptedQuantity * item.unitRate : item.acceptedQuantity), 0); if (accepted.length && totalBasis <= 0) throw new Error("Landed-cost allocation basis is zero.");
    const balanceRefs = accepted.map((item) => db.collection("inventory_balances").doc(key(parsed.locationId, item.itemId, item.batchNumber))); const balanceSnapshots = await Promise.all(balanceRefs.map((ref) => transaction.get(ref)));
    const transactionRefs = accepted.map(() => db.collection("stock_transactions").doc());
    const receiptLines = parsed.items.map((item) => {
      const basis = parsed.allocationBasis === "VALUE" ? item.acceptedQuantity * item.unitRate : item.acceptedQuantity; const allocation = parsed.allocationBasis === "MANUAL" ? number(item.manualFreightAllocation) : totalBasis ? (parsed.freightActual + parsed.handlingActual) * basis / totalBasis : 0; const materialCost = item.acceptedQuantity * item.unitRate; return { item_id: item.itemId, received_quantity: item.receivedQuantity, accepted_quantity: item.acceptedQuantity, rejected_quantity: item.rejectedQuantity, unit: item.unit, unit_rate: item.unitRate, batch_number: item.batchNumber, expiry_date: item.expiryDate || null, quality_status: item.qualityStatus, material_cost: materialCost, allocated_freight_handling: allocation, landed_cost_per_unit: item.acceptedQuantity ? (materialCost + allocation) / item.acceptedQuantity : 0 };
    });
    accepted.forEach((item, index) => { const line = receiptLines.find((entry) => entry.item_id === item.itemId && entry.batch_number === item.batchNumber)!; const snapshot = balanceSnapshots[index]; const previous = number(snapshot.get("current_stock")); const previousCost = number(snapshot.get("weighted_average_cost")); const next = previous + item.acceptedQuantity; const weightedCost = next ? (previous * previousCost + item.acceptedQuantity * item.unitRate) / next : 0; transaction.set(balanceRefs[index], { item_id: item.itemId, location_id: parsed.locationId, batch_number: item.batchNumber, expiry_date: item.expiryDate || null, current_stock: next, reserved_stock: number(snapshot.get("reserved_stock")), available_stock: number(snapshot.get("available_stock")) + item.acceptedQuantity, in_transit_stock: number(snapshot.get("in_transit_stock")), unit: item.unit, weighted_average_cost: weightedCost, landed_cost_per_unit: line.landed_cost_per_unit, last_transaction_at: FieldValue.serverTimestamp(), updated_at: FieldValue.serverTimestamp() }, { merge: true }); transaction.create(transactionRefs[index], { transaction_id: transactionRefs[index].id, transaction_type: "RECEIPT", item_id: item.itemId, location_id: parsed.locationId, quantity: item.acceptedQuantity, unit: item.unit, previous_stock: previous, new_stock: next, cost_per_unit: item.unitRate, landed_cost_per_unit: line.landed_cost_per_unit, total_cost: item.acceptedQuantity * line.landed_cost_per_unit, reference_id: grnRef.id, reference_type: "GRN", batch_number: item.batchNumber, expiry_date: item.expiryDate || null, performed_by: actorId, performed_at: FieldValue.serverTimestamp() }); });
    const totalReceived = receiptLines.reduce((sum, line) => sum + line.accepted_quantity, 0); const grn = { grn_id: grnRef.id, grn_number: `GRN-${Date.now()}-${grnRef.id.slice(0, 5).toUpperCase()}`, po_id: parsed.poId, inbound_shipment_id: parsed.inboundShipmentId || null, location_id: parsed.locationId, receipt_date: parsed.receiptDate, invoice_number: parsed.invoiceNumber, freight_actual: parsed.freightActual, handling_actual: parsed.handlingActual, allocation_basis: parsed.allocationBasis, items: receiptLines, document_urls: parsed.documentUrls, received_by: actorId, created_at: FieldValue.serverTimestamp() }; transaction.create(grnRef, grn);
    const poLines: Array<Record<string, unknown>> = (po.get("items") as Array<Record<string, unknown>>).map((poLine) => { const received = receiptLines.filter((line) => line.item_id === poLine.item_id).reduce((sum, line) => sum + line.accepted_quantity, 0); return { ...poLine, received_quantity: number(poLine.received_quantity) + received }; }); const complete = poLines.every((line) => number(line.received_quantity) >= number(line.ordered_quantity)); transaction.update(poRef, { items: poLines, status: complete ? "RECEIVED" : "PARTIALLY_RECEIVED", updated_at: FieldValue.serverTimestamp() }); return { grnId: grnRef.id, grnNumber: grn.grn_number, status: complete ? "RECEIVED" : "PARTIALLY_RECEIVED", totalReceived };
  }); await writeAudit(actorId, "grn.create", "goods_receipt", result.grnId, null, result, { poId: parsed.poId }); return result;
}
