"use client";
import Link from "next/link";
import { useCallback, useState } from "react";
import ParentAuth from "@/components/ParentAuth";
import { firebaseAuth } from "@/lib/firebase-client";
import { franchiseApplicationStatuses, type FranchiseApplication, type FranchiseApplicationStatus } from "@/lib/franchise-types";
type Summary = Record<string, number | boolean>;
const labels: Record<FranchiseApplicationStatus, string> = { RECEIVED: "Received", UNDER_REVIEW: "Under review", SHORTLISTED: "Shortlisted", APPROVED_FOR_PAYMENT: "Approved for payment", REJECTED: "Rejected", PAID: "Paid", ACTIVATED: "Activated" };
const summaryLabels: Record<string, string> = { targetFranchises: "Target franchises", applications: "Applications", underReview: "Under review", approvedForPayment: "Approved for payment", paymentLinksIssued: "Payment links issued", paid: "Paid", activated: "Activated", availableTerritories: "Available territories", allocatedTerritories: "Allocated territories" };
const money = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);
const date = (value: string | null) => value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeZone: "Asia/Kolkata" }).format(new Date(value)) : "—";
export default function FranchiseApplicationLookup() {
  const [authorized, setAuthorized] = useState(false); const [applications, setApplications] = useState<FranchiseApplication[]>([]); const [summary, setSummary] = useState<Summary>({}); const [message, setMessage] = useState(""); const [busy, setBusy] = useState("");
  const load = useCallback(async () => { const token = await firebaseAuth()?.currentUser?.getIdToken(true); if (!token) throw new Error("Your administrator session has expired."); const response = await fetch("/api/admin/franchise-applications", { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Unable to load applications."); setApplications(payload.applications || []); setSummary(payload.summary || {}); }, []);
  const authChanged = useCallback(async (phone: string | null) => { if (!phone) { setAuthorized(false); return; } const claims = await firebaseAuth()?.currentUser?.getIdTokenResult(true); const roles = Array.isArray(claims?.claims.roles) ? claims.claims.roles : []; const admin = claims?.claims.admin === true || roles.includes("admin"); setAuthorized(admin); if (!admin) return setMessage("This internal page requires administrator access."); try { await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load applications."); } }, [load]);
  async function update(item: FranchiseApplication, status: FranchiseApplicationStatus) { setBusy(item.referenceId); setMessage(""); try { const token = await firebaseAuth()?.currentUser?.getIdToken(true); const response = await fetch("/api/admin/franchise-applications", { method: "PUT", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ referenceId: item.referenceId, status, notes: item.notes, assignedTo: item.assignedTo }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to update application."); } finally { setBusy(""); } }
  async function activate(item: FranchiseApplication) { setBusy(item.referenceId); setMessage(""); try { const token = await firebaseAuth()?.currentUser?.getIdToken(true); const response = await fetch(`/api/admin/franchise-applications/${item.referenceId}/activate`, { method: "POST", headers: { Authorization: `Bearer ${token}` } }); const body = await response.json(); if (!response.ok) throw new Error(body.error); await load(); setMessage(`Franchise ${body.franchiseId} activated.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to activate franchise."); } finally { setBusy(""); } }
  const workflow = franchiseApplicationStatuses.filter((status) => status !== "PAID" && status !== "ACTIVATED");
  return <main className="franchise-admin-page"><header className="topbar"><Link className="brand" href="/"><span className="brand-mark">L</span><span>Lunch<span>Box</span></span></Link><span className="internal-pill">Internal admin</span></header><section className="franchise-admin-shell"><div className="franchise-admin-heading"><div><span className="kicker">FRANCHISE ADMINISTRATION</span><h1>Applications and finance</h1></div><p>Review applicants, authorize payment, and activate verified paid franchise operators.</p></div><section className="admin-auth-panel"><div><b>Secure access</b><span>Firebase administrator role required.</span></div><ParentAuth onChange={(phone) => void authChanged(phone)} /></section>
    {authorized && <><section className="franchise-summary-grid">{Object.entries(summaryLabels).map(([key, label]) => <article key={key}><small>{label}</small><b>{Number(summary[key] || 0).toLocaleString("en-IN")}</b></article>)}</section><section className="franchise-summary-grid"><article><small>Franchise payment amount</small><b>{money(Number(summary.franchisePaymentAmount || 0))}</b></article><article><small>Payments collected</small><b>{money(Number(summary.paymentsCollected || 0))}</b></article><article><small>Payments pending</small><b>{money(Number(summary.paymentsPending || 0))}</b></article><article><small>Paid applications</small><b>{Number(summary.paidApplications || 0)}</b></article><article><small>Refunds</small><b>{Number(summary.refunds || 0)}</b></article></section>{summary.liveMode === false && <p className="franchise-message">Test-mode Razorpay transactions are excluded from production revenue.</p>}
      <div className="franchise-admin-table"><table><thead><tr><th>Reference ID</th><th>Applicant / company</th><th>Territory</th><th>City</th><th>Phone / email</th><th>Application</th><th>Payment</th><th>Link</th><th>Created</th><th>Amount</th><th>Actions</th></tr></thead><tbody>{applications.map((item) => <tr key={item.referenceId}><td><b>{item.referenceId}</b></td><td>{item.applicantName}<small>{item.companyName || "—"}</small></td><td>{item.opportunityId || item.area || "—"}</td><td>{item.selectedCity || "—"}</td><td>{item.phone}<small>{item.email}</small></td><td>{labels[item.status]}</td><td>{item.paymentStatus.replaceAll("_", " ")}</td><td>{item.razorpayStatus || "Not issued"}</td><td>{date(item.submittedAt)}</td><td>{money(item.amountInr || Number(summary.franchisePaymentAmount || 0))}</td><td><select value={item.status} aria-label={`Status for ${item.referenceId}`} disabled={busy === item.referenceId || item.status === "PAID" || item.status === "ACTIVATED"} onChange={(event) => void update(item, event.target.value as FranchiseApplicationStatus)}>{workflow.map((status) => <option key={status} value={status}>{labels[status]}</option>)}{["PAID", "ACTIVATED"].includes(item.status) && <option value={item.status}>{labels[item.status]}</option>}</select>{item.paymentStatus === "PAID" && item.status !== "ACTIVATED" && <button onClick={() => void activate(item)} disabled={busy === item.referenceId}>Activate Franchise</button>}{item.razorpayShortUrl && <a href={item.razorpayShortUrl} target="_blank" rel="noreferrer">Open link</a>}</td></tr>)}</tbody></table></div>{!applications.length && <p className="franchise-message">No franchise applications have been submitted.</p>}</>}{message && <p className="admin-access-error" role="status">{message}</p>}</section></main>;
}
