"use client";
import { useEffect, useState } from "react";
import { onAuthStateChanged, signInWithEmailAndPassword, signOut, type User } from "firebase/auth";
import { firebaseAuth, isFirebaseClientConfigured } from "@/lib/firebase-client";
import type { FranchiseStudent } from "@/lib/students";
export default function FranchiseStudentRoster({ franchiseId }: { franchiseId: string }) {
  const auth = firebaseAuth(); const [user, setUser] = useState<User | null>(null); const [students, setStudents] = useState<FranchiseStudent[]>([]); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => auth ? onAuthStateChanged(auth, setUser) : undefined, [auth]);
  useEffect(() => { if (!user) return; user.getIdToken().then((token) => fetch(`/api/franchises/${encodeURIComponent(franchiseId)}/students`, { headers: { Authorization: `Bearer ${token}` } })).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setStudents(body.students); }).catch((error) => setMessage(error.message)); }, [user, franchiseId]);
  if (!isFirebaseClientConfigured || !auth) return <section className="student-roster"><p>Franchise sign-in is not configured.</p></section>;
  if (!user) return <section className="student-roster"><span className="kicker">RESTRICTED</span><h2>Franchise student roster</h2><p>Sign in with an authorized admin or franchise account to view student data.</p><form onSubmit={async (event) => { event.preventDefault(); try { await signInWithEmailAndPassword(auth, email, password); } catch { setMessage("Unable to sign in."); } }}><input value={email} onChange={(e) => setEmail(e.target.value)} type="email" placeholder="Email" required /><input value={password} onChange={(e) => setPassword(e.target.value)} type="password" placeholder="Password" required /><button>Sign in</button></form>{message && <p role="alert">{message}</p>}</section>;
  return <section className="student-roster"><div><span className="kicker">RESTRICTED</span><h2>Students assigned to this franchise</h2><p>{students.length} enrolled students · <button onClick={() => signOut(auth)}>Sign out</button></p></div>{message ? <p role="alert">{message}</p> : <div className="student-table-wrap"><table><thead><tr><th>Name</th><th>School</th><th>Standard</th><th>Section</th><th>Parent contact</th><th>Diet</th><th>Allergies</th><th>Status</th></tr></thead><tbody>{students.map((student) => <tr key={student.id}><td>{student.name}</td><td>{student.school}</td><td>{student.standard}</td><td>{student.section}</td><td>{student.parentContact}</td><td>{student.dietaryPreference}</td><td>{student.allergies}</td><td>{student.subscriptionStatus}</td></tr>)}</tbody></table></div>}</section>;
}
