"use client";

import { useEffect, useMemo, useState } from "react";
import MarketingLeadPicker from "@/components/MarketingLeadPicker";
import { marketingCities, marketingGeography, type MarketingCity, type MarketingLead } from "@/lib/marketing";
import {
  activityDirections, activityOutcomeLabels, activityOutcomes, activityTypeLabels, activityTypes,
  buildMarketingSeeds, createId, eventStatusLabels, eventStatuses, eventTypeLabels, eventTypes,
  outcomeToLeadStage,
  type MarketingEvent, type MarketingEventStatus, type OutreachActivity, type OutreachActivityType, type OutreachOutcome,
} from "@/lib/marketing-events";
import styles from "./MarketingEvents.module.css";
import cardStyles from "./MarketingEventCard.module.css";

type PipelineLead = MarketingLead & { stage: "New" | "Contacted" | "Interested" | "Meeting" };
type Props = { leads: PipelineLead[]; events: MarketingEvent[]; activities: OutreachActivity[]; onEventsChange: (events: MarketingEvent[]) => void; onActivitiesChange: (activities: OutreachActivity[]) => void; initialLeadId?: string; onLeadStageChange: (leadId: string, stage: PipelineLead["stage"]) => void; onInitialLeadHandled?: () => void };
type EventView = "list" | "calendar";

const today = () => new Date().toISOString().slice(0, 10);
const pretty = (value: string) => new Date(`${value}T00:00:00`).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" });
const eventDefaults = (city: MarketingCity): Omit<MarketingEvent, "eventId" | "createdAt" | "updatedAt"> => {
  const zone = Object.keys(marketingGeography[city])[0];
  const areas = (marketingGeography[city] as Record<string, readonly string[]>)[zone];
  return { title: "", eventType: "TASTING_DAY", city, zone, area: areas[0], linkedLeadIds: [], scheduledDate: today(), scheduledTimeStart: "10:00", scheduledTimeEnd: "12:00", venue: "", ownerName: "", status: "PLANNED", expectedAttendance: undefined, actualAttendance: undefined, leadsGeneratedCount: undefined, notes: "" };
};

export default function MarketingEvents({ leads, events, activities, onEventsChange, onActivitiesChange, initialLeadId, onLeadStageChange, onInitialLeadHandled }: Props) {
  const [eventView, setEventView] = useState<EventView>("list"); const [eventCity, setEventCity] = useState<"ALL" | MarketingCity>("ALL"); const [eventStatus, setEventStatus] = useState<"ALL" | MarketingEventStatus>("ALL");
  const [activityLead, setActivityLead] = useState("ALL"); const [activityType, setActivityType] = useState<"ALL" | OutreachActivityType>("ALL"); const [activityOutcome, setActivityOutcome] = useState<"ALL" | OutreachOutcome>("ALL");
  const [eventSearch, setEventSearch] = useState(""); const [eventFrom, setEventFrom] = useState(""); const [eventTo, setEventTo] = useState("");
  const [activityFrom, setActivityFrom] = useState(""); const [activityTo, setActivityTo] = useState("");
  const [showEventForm, setShowEventForm] = useState(false); const [showActivityForm, setShowActivityForm] = useState(false);
  const [editingEventId, setEditingEventId] = useState("");
  const [editingActivityId, setEditingActivityId] = useState("");
  const [eventDraft, setEventDraft] = useState(eventDefaults("Chennai"));
  const [activityDraft, setActivityDraft] = useState({ leadId: "", linkedEventId: "", activityType: "CALL" as OutreachActivityType, direction: "OUTBOUND" as "OUTBOUND" | "INBOUND", outcome: "FOLLOW_UP_NEEDED" as OutreachOutcome, notes: "", performedBy: "", performedAt: new Date().toISOString().slice(0, 16), nextFollowUpDate: "" });
  const [completionId, setCompletionId] = useState(""); const [completion, setCompletion] = useState({ actualAttendance: "", leadsGeneratedCount: "" });

  useEffect(() => { if (!initialLeadId) return; setActivityDraft((value) => ({ ...value, leadId: initialLeadId })); setShowActivityForm(true); onInitialLeadHandled?.(); }, [initialLeadId, onInitialLeadHandled]);
  const saveEvents = onEventsChange;
  const saveActivities = onActivitiesChange;

  const leadById = useMemo(() => new Map(leads.map((lead) => [lead.id, lead])), [leads]);
  const filteredEvents = useMemo(() => events.filter((event) => (eventCity === "ALL" || event.city === eventCity) && (eventStatus === "ALL" || event.status === eventStatus) && (!eventFrom || event.scheduledDate >= eventFrom) && (!eventTo || event.scheduledDate <= eventTo) && (!eventSearch || `${event.title} ${event.venue} ${event.area}`.toLowerCase().includes(eventSearch.toLowerCase()))).sort((a, b) => a.scheduledDate.localeCompare(b.scheduledDate)), [events, eventCity, eventStatus, eventFrom, eventTo, eventSearch]);
  const filteredActivities = useMemo(() => activities.filter((activity) => (activityLead === "ALL" || activity.leadId === activityLead) && (activityType === "ALL" || activity.activityType === activityType) && (activityOutcome === "ALL" || activity.outcome === activityOutcome) && (!activityFrom || activity.performedAt.slice(0, 10) >= activityFrom) && (!activityTo || activity.performedAt.slice(0, 10) <= activityTo)).sort((a, b) => b.performedAt.localeCompare(a.performedAt)), [activities, activityLead, activityType, activityOutcome, activityFrom, activityTo]);
  const dueFollowUps = useMemo(() => activities.filter((activity) => activity.nextFollowUpDate && activity.nextFollowUpDate <= today() && !activities.some((newer) => newer.leadId === activity.leadId && newer.performedAt > activity.performedAt)), [activities]);
  const now = new Date(); const month = now.toISOString().slice(0, 7); const inThirtyDays = new Date(now); inThirtyDays.setDate(inThirtyDays.getDate() + 30); const weekAgo = new Date(now); weekAgo.setDate(weekAgo.getDate() - 7);
  const stats = [
    ["Upcoming events", events.filter((event) => ["PLANNED", "CONFIRMED"].includes(event.status) && event.scheduledDate >= today() && new Date(`${event.scheduledDate}T23:59:59`) <= inThirtyDays).length, "Next 30 days"],
    ["Events this month", events.filter((event) => event.scheduledDate.startsWith(month)).length, now.toLocaleDateString("en-IN", { month: "long" })],
    ["Outreach this week", activities.filter((activity) => new Date(activity.performedAt) >= weekAgo).length, "Last 7 days"],
    ["Follow-ups due", dueFollowUps.length, "Today and overdue"],
  ] as const;

  function changeEventCity(city: MarketingCity) { const zone = Object.keys(marketingGeography[city])[0]; const areas = (marketingGeography[city] as Record<string, readonly string[]>)[zone]; setEventDraft((value) => ({ ...value, city, zone, area: areas[0] })); }
  function changeEventZone(zone: string) { const areas = (marketingGeography[eventDraft.city] as Record<string, readonly string[]>)[zone] || []; setEventDraft((value) => ({ ...value, zone, area: areas[0] || "" })); }
  function resetEventForm() { setEditingEventId(""); setEventDraft(eventDefaults(eventDraft.city)); setShowEventForm(false); }
  function openNewEventForm() { setEditingEventId(""); setEventDraft(eventDefaults(eventDraft.city)); setShowEventForm(true); }
  function scheduleEvent(event: React.FormEvent) { event.preventDefault(); const timestamp = new Date().toISOString(); if (editingEventId) { saveEvents(events.map((item) => item.eventId === editingEventId ? { ...item, ...eventDraft, updatedAt: timestamp } : item)); } else { saveEvents([...events, { ...eventDraft, eventId: createId("event"), createdAt: timestamp, updatedAt: timestamp }]); } resetEventForm(); }
  function editEvent(event: MarketingEvent) { setEditingEventId(event.eventId); setEventDraft({ title: event.title, eventType: event.eventType, city: event.city, zone: event.zone, area: event.area, linkedLeadIds: [...event.linkedLeadIds], scheduledDate: event.scheduledDate, scheduledTimeStart: event.scheduledTimeStart, scheduledTimeEnd: event.scheduledTimeEnd, venue: event.venue, ownerName: event.ownerName, status: event.status, expectedAttendance: event.expectedAttendance, actualAttendance: event.actualAttendance, leadsGeneratedCount: event.leadsGeneratedCount, notes: event.notes }); setShowEventForm(true); }
  function deleteEvent(event: MarketingEvent) { if (!window.confirm(`Delete “${event.title}”? Outreach activities will remain in the activity log.`)) return; saveEvents(events.filter((item) => item.eventId !== event.eventId)); if (editingEventId === event.eventId) resetEventForm(); }
  function updateEventStatus(event: MarketingEvent, status: MarketingEventStatus) { if (status === "COMPLETED" && (event.actualAttendance == null || event.leadsGeneratedCount == null)) { setCompletionId(event.eventId); setCompletion({ actualAttendance: event.actualAttendance?.toString() || "", leadsGeneratedCount: event.leadsGeneratedCount?.toString() || "" }); return; } saveEvents(events.map((item) => item.eventId === event.eventId ? { ...item, status, updatedAt: new Date().toISOString() } : item)); }
  function completeEvent(event: React.FormEvent) { event.preventDefault(); saveEvents(events.map((item) => item.eventId === completionId ? { ...item, status: "COMPLETED", actualAttendance: Number(completion.actualAttendance), leadsGeneratedCount: Number(completion.leadsGeneratedCount), updatedAt: new Date().toISOString() } : item)); setCompletionId(""); }
  function resetActivityForm() { setEditingActivityId(""); setActivityDraft((value) => ({ ...value, leadId: "", linkedEventId: "", notes: "", nextFollowUpDate: "", performedAt: new Date().toISOString().slice(0, 16) })); setShowActivityForm(false); }
  function logActivity(event: React.FormEvent) { event.preventDefault(); if (!activityDraft.leadId) return; const timestamp = new Date().toISOString(); const values = { ...activityDraft, linkedEventId: activityDraft.linkedEventId || undefined, nextFollowUpDate: activityDraft.nextFollowUpDate || undefined, performedAt: new Date(activityDraft.performedAt).toISOString() }; if (editingActivityId) { saveActivities(activities.map((activity) => activity.activityId === editingActivityId ? { ...activity, ...values } : activity)); } else { saveActivities([...activities, { ...values, activityId: createId("activity"), createdAt: timestamp }]); } onLeadStageChange(values.leadId, outcomeToLeadStage(values.outcome)); resetActivityForm(); }
  function updateActivityOutcome(activityId: string, outcome: OutreachOutcome) { const activity = activities.find((item) => item.activityId === activityId); if (!activity) return; saveActivities(activities.map((item) => item.activityId === activityId ? { ...item, outcome } : item)); onLeadStageChange(activity.leadId, outcomeToLeadStage(outcome)); }
  function editActivity(activity: OutreachActivity) { setEditingActivityId(activity.activityId); setActivityDraft({ leadId: activity.leadId, linkedEventId: activity.linkedEventId || "", activityType: activity.activityType, direction: activity.direction, outcome: activity.outcome, notes: activity.notes, performedBy: activity.performedBy, performedAt: new Date(activity.performedAt).toISOString().slice(0, 16), nextFollowUpDate: activity.nextFollowUpDate || "" }); setShowActivityForm(true); }
  function deleteActivity(activity: OutreachActivity) { if (!window.confirm(`Delete this ${activityTypeLabels[activity.activityType].toLowerCase()} activity for ${leadById.get(activity.leadId)?.name || "this lead"}?`)) return; saveActivities(activities.filter((item) => item.activityId !== activity.activityId)); if (editingActivityId === activity.activityId) resetActivityForm(); }
  function loadSamples() { const sample = buildMarketingSeeds(leads); saveEvents(sample.events); saveActivities(sample.activities); sample.activities.forEach((activity) => { if (leadById.has(activity.leadId)) onLeadStageChange(activity.leadId, outcomeToLeadStage(activity.outcome)); }); }

  const eventZones = Object.keys(marketingGeography[eventDraft.city]); const eventAreas = (marketingGeography[eventDraft.city] as Record<string, readonly string[]>)[eventDraft.zone] || [];
  const calendarGroups = Object.entries(Object.groupBy(filteredEvents, (event) => event.scheduledDate));

  return <section className={styles.workspace}>
    <div className={styles.stats}>{stats.map(([label, value, note]) => <article key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</div>

    <section className={styles.section}>
      <header className={styles.sectionHead}><div><span>SCHEDULED EVENTS</span><h2>Plan real-world marketing moments.</h2><p>Tastings, PTA stalls, sampling stands and community conversations.</p></div><button onClick={() => showEventForm ? resetEventForm() : openNewEventForm()}>+ Schedule an event</button></header>
      <div className={styles.toolbar}><div className={styles.chips}><button className={eventView === "list" ? styles.activeChip : ""} onClick={() => setEventView("list")}>List</button><button className={eventView === "calendar" ? styles.activeChip : ""} onClick={() => setEventView("calendar")}>Calendar</button></div><input type="search" value={eventSearch} onChange={(event) => setEventSearch(event.target.value)} placeholder="Search events or venues" aria-label="Search events" /><select value={eventCity} onChange={(event) => setEventCity(event.target.value as typeof eventCity)}><option value="ALL">All cities</option>{marketingCities.map((city) => <option key={city}>{city}</option>)}</select><select value={eventStatus} onChange={(event) => setEventStatus(event.target.value as typeof eventStatus)}><option value="ALL">All statuses</option>{eventStatuses.map((status) => <option value={status} key={status}>{eventStatusLabels[status]}</option>)}</select><label>From<input type="date" value={eventFrom} onChange={(event) => setEventFrom(event.target.value)} /></label><label>To<input type="date" value={eventTo} onChange={(event) => setEventTo(event.target.value)} /></label></div>
      {showEventForm && <form className={styles.form} onSubmit={scheduleEvent}><h3>{editingEventId ? "Edit event" : "Schedule an event"}</h3><label className={styles.wide}>Title<input required value={eventDraft.title} onChange={(event) => setEventDraft({ ...eventDraft, title: event.target.value })} placeholder="Adyar Pilot School tasting day" /></label><label>Type<select value={eventDraft.eventType} onChange={(event) => setEventDraft({ ...eventDraft, eventType: event.target.value as MarketingEvent["eventType"] })}>{eventTypes.map((type) => <option value={type} key={type}>{eventTypeLabels[type]}</option>)}</select></label><label>Status<select value={eventDraft.status} onChange={(event) => setEventDraft({ ...eventDraft, status: event.target.value as MarketingEventStatus })}>{eventStatuses.filter((status) => status !== "COMPLETED" || eventDraft.status === "COMPLETED").map((status) => <option value={status} key={status}>{eventStatusLabels[status]}</option>)}</select></label>
        <fieldset className={styles.location}><legend>Location</legend><div className={styles.chips}>{marketingCities.map((city) => <button type="button" className={eventDraft.city === city ? styles.activeChip : ""} key={city} onClick={() => changeEventCity(city)}>{city}</button>)}</div><div className={styles.chips}>{eventZones.map((zone) => <button type="button" className={eventDraft.zone === zone ? styles.activeChip : ""} key={zone} onClick={() => changeEventZone(zone)}>{zone}</button>)}</div><div className={styles.chips}>{eventAreas.map((area) => <button type="button" className={eventDraft.area === area ? styles.activeChip : ""} key={area} onClick={() => setEventDraft({ ...eventDraft, area })}>{area}</button>)}</div></fieldset>
        <label>Date<input type="date" required value={eventDraft.scheduledDate} onChange={(event) => setEventDraft({ ...eventDraft, scheduledDate: event.target.value })} /></label><label>Start<input type="time" required value={eventDraft.scheduledTimeStart} onChange={(event) => setEventDraft({ ...eventDraft, scheduledTimeStart: event.target.value })} /></label><label>End<input type="time" required value={eventDraft.scheduledTimeEnd} onChange={(event) => setEventDraft({ ...eventDraft, scheduledTimeEnd: event.target.value })} /></label><label>Expected attendance<input type="number" min="0" value={eventDraft.expectedAttendance ?? ""} onChange={(event) => setEventDraft({ ...eventDraft, expectedAttendance: event.target.value ? Number(event.target.value) : undefined })} /></label><label>Venue<input required value={eventDraft.venue} onChange={(event) => setEventDraft({ ...eventDraft, venue: event.target.value })} /></label><label>Owner<input required value={eventDraft.ownerName} onChange={(event) => setEventDraft({ ...eventDraft, ownerName: event.target.value })} /></label>
        <div className={styles.leadPicker}><MarketingLeadPicker leads={leads} selectedIds={eventDraft.linkedLeadIds} multiple label="Link pipeline leads" onChange={(linkedLeadIds) => setEventDraft({ ...eventDraft, linkedLeadIds })} /></div><label className={styles.wide}>Notes<textarea value={eventDraft.notes} onChange={(event) => setEventDraft({ ...eventDraft, notes: event.target.value })} /></label><div className={styles.formActions}><button type="button" onClick={resetEventForm}>Cancel</button><button type="submit">{editingEventId ? "Save changes" : "Schedule event"}</button></div></form>}
      {filteredEvents.length ? eventView === "list" ? <div className={styles.eventGrid}>{filteredEvents.map((event) => <EventCard key={event.eventId} event={event} leads={leadById} onStatus={updateEventStatus} onEdit={editEvent} onDelete={deleteEvent} />)}</div> : <div className={styles.calendar}>{calendarGroups.map(([date, dateEvents]) => <article key={date}><time>{pretty(date)}</time>{dateEvents?.map((event) => <div key={event.eventId}><b>{event.scheduledTimeStart}</b><span>{event.title}</span><small>{eventStatusLabels[event.status]}</small></div>)}</article>)}</div> : <Empty title="No events scheduled yet." text="Plan your first tasting, PTA stall, campus sampling stand, or community talk." action="Schedule an event" onAction={openNewEventForm} secondary="Load sample data" onSecondary={loadSamples} />}
      {completionId && <form className={styles.completion} onSubmit={completeEvent}><h3>Complete this event</h3><p>Add the actual result before marking it completed.</p><label>Actual attendance<input type="number" min="0" required value={completion.actualAttendance} onChange={(event) => setCompletion({ ...completion, actualAttendance: event.target.value })} /></label><label>Leads generated<input type="number" min="0" required value={completion.leadsGeneratedCount} onChange={(event) => setCompletion({ ...completion, leadsGeneratedCount: event.target.value })} /></label><button type="button" onClick={() => setCompletionId("")}>Cancel</button><button type="submit">Mark completed</button></form>}
    </section>

    <section className={styles.section}>
      <header className={styles.sectionHead}><div><span>OUTREACH ACTIVITY LOG</span><h2>Keep every real conversation connected.</h2><p>Calls, email, WhatsApp and in-person touches against saved pipeline leads.</p></div><button onClick={() => setShowActivityForm((value) => !value)}>+ Log an activity</button></header>
      {dueFollowUps.length > 0 && <div className={styles.reminders}><strong>{dueFollowUps.length} follow-up{dueFollowUps.length === 1 ? "" : "s"} due</strong>{dueFollowUps.map((activity) => <span key={activity.activityId}>{leadById.get(activity.leadId)?.name || "Missing lead"} · {pretty(activity.nextFollowUpDate!)}</span>)}</div>}
      <div className={styles.toolbar}><select value={activityLead} onChange={(event) => setActivityLead(event.target.value)}><option value="ALL">All leads</option>{leads.map((lead) => <option value={lead.id} key={lead.id}>{lead.name}</option>)}</select><select value={activityType} onChange={(event) => setActivityType(event.target.value as typeof activityType)}><option value="ALL">All activity types</option>{activityTypes.map((type) => <option value={type} key={type}>{activityTypeLabels[type]}</option>)}</select><select value={activityOutcome} onChange={(event) => setActivityOutcome(event.target.value as typeof activityOutcome)}><option value="ALL">All outcomes</option>{activityOutcomes.map((outcome) => <option value={outcome} key={outcome}>{activityOutcomeLabels[outcome]}</option>)}</select><label>From<input type="date" value={activityFrom} onChange={(event) => setActivityFrom(event.target.value)} /></label><label>To<input type="date" value={activityTo} onChange={(event) => setActivityTo(event.target.value)} /></label></div>
      {showActivityForm && <form className={styles.form} onSubmit={logActivity}><h3>{editingActivityId ? "Edit activity" : "Log an activity"}</h3><label>Lead<select required value={activityDraft.leadId} onChange={(event) => setActivityDraft({ ...activityDraft, leadId: event.target.value })}><option value="">Choose a saved lead</option>{leads.map((lead) => <option value={lead.id} key={lead.id}>{lead.name}</option>)}</select></label><label>Related event<select value={activityDraft.linkedEventId} onChange={(event) => setActivityDraft({ ...activityDraft, linkedEventId: event.target.value })}><option value="">No linked event</option>{events.map((event) => <option value={event.eventId} key={event.eventId}>{event.title}</option>)}</select></label><label>Activity type<select value={activityDraft.activityType} onChange={(event) => setActivityDraft({ ...activityDraft, activityType: event.target.value as OutreachActivityType })}>{activityTypes.map((type) => <option value={type} key={type}>{activityTypeLabels[type]}</option>)}</select></label><label>Direction<select value={activityDraft.direction} onChange={(event) => setActivityDraft({ ...activityDraft, direction: event.target.value as "OUTBOUND" | "INBOUND" })}>{activityDirections.map((direction) => <option value={direction} key={direction}>{direction === "OUTBOUND" ? "Outbound" : "Inbound"}</option>)}</select></label><label>Outcome<select value={activityDraft.outcome} onChange={(event) => setActivityDraft({ ...activityDraft, outcome: event.target.value as OutreachOutcome })}>{activityOutcomes.map((outcome) => <option value={outcome} key={outcome}>{activityOutcomeLabels[outcome]}</option>)}</select></label><label>Performed by<input required value={activityDraft.performedBy} onChange={(event) => setActivityDraft({ ...activityDraft, performedBy: event.target.value })} /></label><label>Performed at<input required type="datetime-local" value={activityDraft.performedAt} onChange={(event) => setActivityDraft({ ...activityDraft, performedAt: event.target.value })} /></label><label>Next follow-up<input type="date" value={activityDraft.nextFollowUpDate} onChange={(event) => setActivityDraft({ ...activityDraft, nextFollowUpDate: event.target.value })} /></label><label className={styles.wide}>Notes<textarea required value={activityDraft.notes} onChange={(event) => setActivityDraft({ ...activityDraft, notes: event.target.value })} /></label><div className={styles.formActions}><button type="button" onClick={resetActivityForm}>Cancel</button><button type="submit">{editingActivityId ? "Save changes" : "Log activity"}</button></div></form>}
      {filteredActivities.length ? <div className={styles.feed}>{filteredActivities.map((activity) => { const event = events.find((item) => item.eventId === activity.linkedEventId); return <article key={activity.activityId}><span className={styles.activityIcon}>{activityTypeLabels[activity.activityType].slice(0, 1)}</span><div><div className={styles.feedMeta}><b>{leadById.get(activity.leadId)?.name || "Deleted lead"}</b><span>{activityTypeLabels[activity.activityType]}</span><label>Activity status<select className={styles.planned} value={activity.outcome} onChange={(change) => updateActivityOutcome(activity.activityId, change.target.value as OutreachOutcome)}>{activityOutcomes.map((outcome) => <option value={outcome} key={outcome}>{activityOutcomeLabels[outcome]}</option>)}</select></label></div><p>{activity.notes}</p><small>{new Date(activity.performedAt).toLocaleString("en-IN")} · {activity.direction === "OUTBOUND" ? "Outbound" : "Inbound"} · {activity.performedBy}{event ? ` · ${event.title}` : ""}</small>{activity.nextFollowUpDate && <em>Follow up {pretty(activity.nextFollowUpDate)}</em>}<div className={styles.formActions}><button type="button" onClick={() => editActivity(activity)}>Edit</button><button type="button" onClick={() => deleteActivity(activity)}>Delete</button></div></div></article>; })}</div> : <Empty title="No outreach activity yet." text="Log a call, email, WhatsApp message, SMS, or in-person visit against a saved lead." action="Log an activity" onAction={() => setShowActivityForm(true)} secondary={!events.length && !activities.length ? "Load sample data" : undefined} onSecondary={loadSamples} />}
    </section>
  </section>;
}

function EventCard({ event, leads, onStatus, onEdit, onDelete }: { event: MarketingEvent; leads: Map<string, PipelineLead>; onStatus: (event: MarketingEvent, status: MarketingEventStatus) => void; onEdit: (event: MarketingEvent) => void; onDelete: (event: MarketingEvent) => void }) {
  return <article className={styles.eventCard}><div className={styles.eventCardTop}><span>{eventTypeLabels[event.eventType]}</span><select className={styles[event.status.toLowerCase()]} value={event.status} onChange={(change) => onStatus(event, change.target.value as MarketingEventStatus)}>{eventStatuses.map((status) => <option value={status} key={status}>{eventStatusLabels[status]}</option>)}</select></div><h3>{event.title}</h3><p><b>{pretty(event.scheduledDate)}</b> · {event.scheduledTimeStart}–{event.scheduledTimeEnd}</p><p>{event.venue}</p><small>{event.city} · {event.area} · {event.ownerName}</small><footer><span className={cardStyles.leadPill}>{event.linkedLeadIds.length} linked lead{event.linkedLeadIds.length === 1 ? "" : "s"}</span>{event.linkedLeadIds.slice(0, 2).map((id) => <span className={cardStyles.leadPill} key={id}>{leads.get(id)?.name || "Deleted lead"}</span>)}<div className={cardStyles.actions}><button onClick={() => onEdit(event)}>Edit</button><button onClick={() => onDelete(event)}>Delete</button></div></footer></article>;
}

function Empty({ title, text, action, onAction, secondary, onSecondary }: { title: string; text: string; action: string; onAction: () => void; secondary?: string; onSecondary?: () => void }) {
  return <div className={styles.empty}><span>◇</span><h3>{title}</h3><p>{text}</p><button onClick={onAction}>{action}</button>{secondary && <button className={styles.secondary} onClick={onSecondary}>{secondary}</button>}</div>;
}
