"use client";
import Link from "next/link";
import { FormEvent, useCallback, useMemo, useState } from "react";
import ParentAuth from "@/components/ParentAuth";
import { firebaseAuth } from "@/lib/firebase-client";
import { mealEnrollmentStatuses, mealEnrollmentTypes, type MealEnrollmentAdmin, type MealEnrollmentType } from "@/lib/meal-enrollment-admin";
import { SCHOOL_CITIES } from "@/lib/school-locator/territories";

const label = (value: string) => value.toLowerCase().replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const typeLabel: Record<MealEnrollmentType, string> = { SCHOOL_CHILD: "School Child", COLLEGE_STUDENT: "College Student", OFFICE_WORKER: "Office Worker" };
const date = (value: string | null) => value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeZone: "Asia/Kolkata" }).format(new Date(value)) : "Not set";
const csv = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`;
type Payload = { registrations?: MealEnrollmentAdmin[]; summary?: Record<string, number>; error?: string };

export default function PartnerRegistrationDashboard() {
  const [authorized, setAuthorized] = useState(false); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const [registrations, setRegistrations] = useState<MealEnrollmentAdmin[]>([]); const [summary, setSummary] = useState<Record<string, number>>({}); const [selected, setSelected] = useState<MealEnrollmentAdmin | null>(null);
  const [type, setType] = useState(""); const [status, setStatus] = useState(""); const [city, setCity] = useState(""); const [zone, setZone] = useState(""); const [query, setQuery] = useState("");
  const zones = useMemo(() => SCHOOL_CITIES.find((item) => item.code === city)?.zones || [], [city]);
  const load = useCallback(async (filters: Record<string, string> = {}) => { setLoading(true); setMessage(""); try { const token = await firebaseAuth()?.currentUser?.getIdToken(true); if (!token) throw new Error("Your administrator session has expired."); const params = new URLSearchParams(Object.entries(filters).filter(([, value]) => value)); const response = await fetch(`/api/admin/registrations?${params}`, { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); const payload = await response.json() as Payload; if (!response.ok) throw new Error(payload.error || "Unable to load meal registrations."); setRegistrations(payload.registrations || []); setSummary(payload.summary || {}); setSelected(null); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load meal registrations."); } finally { setLoading(false); } }, []);
  const authChanged = useCallback(async (phone: string | null) => { setRegistrations([]); setSelected(null); setMessage(""); if (!phone) return setAuthorized(false); const claims = await firebaseAuth()?.currentUser?.getIdTokenResult(true); const roles = Array.isArray(claims?.claims.roles) ? claims.claims.roles : []; const admin = claims?.claims.admin === true || roles.includes("admin"); setAuthorized(admin); if (admin) await load(); else setMessage("This internal page requires administrator access."); }, [load]);
  function filter(event: FormEvent) { event.preventDefault(); void load({ type, status, city, zone, q: query }); }
  async function update(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; setSaving(true); setMessage(""); try { const token = await firebaseAuth()?.currentUser?.getIdToken(true); const form = new FormData(event.currentTarget); const response = await fetch("/api/admin/registrations", { method: "PUT", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ registrationId: selected.registrationId, status: form.get("status"), assignedTo: form.get("assigned_to"), followUpDate: form.get("follow_up_date"), notes: form.get("notes") }) }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error || "Unable to update registration."); setMessage("Meal registration updated."); await load({ type, status, city, zone, q: query }); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to update registration."); } finally { setSaving(false); } }
  function exportCsv() { const rows = [["Reference", "Type", "Person", "Parent", "Location", "Phone", "Status", "Created"], ...registrations.map((item) => [item.registrationId, typeLabel[item.registrationType], item.personName, item.guardianName, item.locationName, item.contactPhone, label(item.status), item.createdAt])]; const blob = new Blob([rows.map((row) => row.map(csv).join(",")).join("\n")], { type: "text/csv;charset=utf-8" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `meal-registrations-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(link.href); }
  return <main className="partner-admin-page"><header className="topbar"><Link className="brand" href="/"><span className="brand-mark">L</span><span>Lunch<span>Box</span></span></Link><nav className="partner-admin-nav"><Link href="/admin">Kitchens</Link><Link className="active" href="/admin/registrations">Meal Registrations</Link><Link href="/admin/franchise-applications">Franchise</Link></nav></header><section className="partner-admin-shell">
    <div className="partner-admin-heading"><div><span className="kicker">INDIVIDUAL MEAL ENROLLMENT</span><h1>Registration console</h1></div><p>Manage children registered by parents, college students, and office workers from one secure queue.</p></div>
    <section className="admin-auth-panel"><div><b>Secure internal access</b><span>Firebase administrator role required.</span></div><ParentAuth onChange={(phone) => void authChanged(phone)} /></section>
    {authorized && <><form className="partner-filters" onSubmit={filter}><label>Registrant<select value={type} onChange={(event) => setType(event.target.value)}><option value="">All types</option>{mealEnrollmentTypes.map((item) => <option value={item} key={item}>{typeLabel[item]}</option>)}</select></label><label>Status<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option>{mealEnrollmentStatuses.map((item) => <option value={item} key={item}>{label(item)}</option>)}</select></label><label>City<select value={city} onChange={(event) => { setCity(event.target.value); setZone(""); }}><option value="">All cities</option>{SCHOOL_CITIES.map((item) => <option value={item.code} key={item.code}>{item.name}</option>)}</select></label><label>Zone<select disabled={!city} value={zone} onChange={(event) => setZone(event.target.value)}><option value="">All zones</option>{zones.map((item) => <option value={item.code} key={item.code}>{item.name}</option>)}</select></label><label className="partner-query">Search<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Person, parent, location, phone" /></label><button className="checkout-button" disabled={loading}>{loading ? "Loading…" : "Apply"}</button><button type="button" className="partner-export" onClick={exportCsv}>Export CSV</button></form>
    <section className="partner-summary">{mealEnrollmentStatuses.map((item) => <article key={item}><span>{label(item)}</span><b>{summary[item] || 0}</b></article>)}</section>{message && <p className="partner-message" role="status">{message}</p>}
    <div className="partner-workspace"><section className="partner-list"><header><h2>Meal registrations</h2><span>{registrations.length} records</span></header>{!loading && !registrations.length && <div className="partner-empty">No registrations match these filters.</div>}{registrations.map((item) => <button type="button" className={selected?.registrationId === item.registrationId ? "selected" : ""} key={item.registrationId} onClick={() => setSelected(item)}><div><span className={`partner-type type-${item.registrationType.toLowerCase()}`}>{typeLabel[item.registrationType]}</span></div><b>{item.personName}</b><small>{item.locationName} · {item.registrationId}</small><span className={`pipeline-status status-${item.status.toLowerCase().replaceAll("_", "-")}`}>{label(item.status)}</span></button>)}</section>
    <section className="partner-detail">{!selected ? <div className="partner-empty"><b>Select a registration</b><span>Review meal and contact details, then update the workflow.</span></div> : <><header><div><span className="partner-type">{typeLabel[selected.registrationType]}</span><h2>{selected.personName}</h2><small>{selected.registrationId}</small></div><span className={`pipeline-status status-${selected.status.toLowerCase().replaceAll("_", "-")}`}>{label(selected.status)}</span></header><div className="partner-detail-grid"><span><small>School / college / workplace</small><b>{selected.locationName}</b><em>{selected.locality || selected.formattedAddress}</em></span><span><small>Contact</small><b>{selected.guardianName || selected.personName}</b><em>{selected.contactPhone} · {selected.contactEmail || "No email"}</em></span><span><small>Class / course / department</small><b>{selected.gradeOrCourse || "Not provided"}</b><em>{selected.identifier || "No ID / section"}</em></span><span><small>Meal preference</small><b>{label(selected.mealPlanInterest || "not provided")}</b><em>{label(selected.dietaryPreference || "not provided")} · {selected.preferredMealTime || "No time"}</em></span><span><small>Allergies / notes</small><b>{selected.allergies || "None provided"}</b></span><span><small>Submitted</small><b>{date(selected.createdAt)}</b></span></div><form className="partner-review-form" onSubmit={update}><label>Status<select name="status" defaultValue={selected.status}>{mealEnrollmentStatuses.map((item) => <option value={item} key={item}>{label(item)}</option>)}</select></label><label>Assigned owner<input name="assigned_to" defaultValue={selected.assignedTo || ""} /></label><label>Follow-up date<input name="follow_up_date" type="date" defaultValue={selected.followUpAt?.slice(0, 10) || ""} /></label><label className="review-notes">Internal notes<textarea name="notes" defaultValue={selected.notes || ""} maxLength={2000} /></label><button className="checkout-button" disabled={saving}>{saving ? "Saving…" : "Save workflow"}</button></form></>}</section></div></>}
    {!authorized && message && <p className="partner-message error">{message}</p>}
  </section></main>;
}
