import { FieldValue } from "@google-cloud/firestore";
import { NextResponse } from "next/server";
import { verifyInventoryAccess } from "@/lib/firebase-admin";
import { firestoreClient } from "@/lib/firestore";
import { apiError, jsonBody } from "@/lib/inventory/api";
import { transportationRateSchema } from "@/lib/inventory/domain";
import { serialize, writeAudit } from "@/lib/inventory/service";
export async function GET(request: Request) { try { await verifyInventoryAccess(request, ["admin", "logistics_manager", "procurement_manager", "finance_analyst"]); const snapshot = await firestoreClient().collection("transportation_rate_master").orderBy("effective_from", "desc").limit(500).get(); return NextResponse.json({ rates: snapshot.docs.map(serialize) }); } catch (error) { return apiError(error); } }
export async function POST(request: Request) { try { const actor = await verifyInventoryAccess(request, ["admin", "logistics_manager"]); const parsed = transportationRateSchema.parse(await jsonBody(request)); const ref = parsed.rateId ? firestoreClient().collection("transportation_rate_master").doc(parsed.rateId) : firestoreClient().collection("transportation_rate_master").doc(); const record = { rate_id: ref.id, mode: parsed.mode, origin_location_id: parsed.originLocationId, destination_location_id: parsed.destinationLocationId, origin_point: parsed.originPoint, destination_point: parsed.destinationPoint, route_distance_km: parsed.routeDistanceKm, commodity_name: parsed.commodityName, commodity_class: parsed.commodityClass, carrier_unit_type: parsed.carrierUnitType, rate_type: parsed.rateType, base_rate: parsed.baseRate, minimum_charge: parsed.minimumCharge, loading_charge: parsed.loadingCharge, unloading_charge: parsed.unloadingCharge, terminal_charge: parsed.terminalCharge, handling_charge: parsed.handlingCharge, insurance_percent: parsed.insurancePercent, tax_percent: parsed.taxPercent, effective_from: parsed.effectiveFrom, effective_to: parsed.effectiveTo || null, source_reference: parsed.sourceReference, status: parsed.status, created_by: actor.uid, created_at: FieldValue.serverTimestamp(), updated_at: FieldValue.serverTimestamp() }; await ref.create(record); await writeAudit(actor.uid, "transport_rate.create", "transport_rate", ref.id, null, record); return NextResponse.json({ rateId: ref.id, status: parsed.status }, { status: 201 }); } catch (error) { return apiError(error); } }
