import { FieldValue } from "@google-cloud/firestore";
import { NextResponse } from "next/server";
import { verifyInventoryAccess } from "@/lib/firebase-admin";
import { firestoreClient } from "@/lib/firestore";
import { apiError, jsonBody } from "@/lib/inventory/api";
import { dailyExpenseSchema } from "@/lib/inventory/domain";
import { serialize, writeAudit } from "@/lib/inventory/service";
export async function GET(request: Request) { try { const locationId = new URL(request.url).searchParams.get("locationId"); const actor = await verifyInventoryAccess(request, ["admin", "branch_store_manager", "kitchen_manager", "finance_analyst"], locationId || undefined); let query: FirebaseFirestore.Query = firestoreClient().collection("daily_expenses"); if (locationId) query = query.where("location_id", "==", locationId); const snapshot = await query.orderBy("expense_date", "desc").limit(500).get(); return NextResponse.json({ expenses: snapshot.docs.map(serialize).filter((expense) => actor.isAdmin || actor.locationIds.includes(String(expense.location_id))) }); } catch (error) { return apiError(error); } }
export async function POST(request: Request) { try { const parsed = dailyExpenseSchema.parse(await jsonBody(request)); const actor = await verifyInventoryAccess(request, ["admin", "branch_store_manager", "kitchen_manager"], parsed.locationId); const ref = parsed.expenseId ? firestoreClient().collection("daily_expenses").doc(parsed.expenseId) : firestoreClient().collection("daily_expenses").doc(); const record = { expense_id: ref.id, location_id: parsed.locationId, expense_date: parsed.expenseDate, category: parsed.category, description: parsed.description, supplier_id: parsed.supplierId || null, amount: parsed.amount, currency: parsed.currency.toUpperCase(), receipt_url: parsed.receiptUrl || null, status: parsed.status, created_by: actor.uid, created_at: FieldValue.serverTimestamp(), updated_at: FieldValue.serverTimestamp() }; await ref.create(record); await writeAudit(actor.uid, "daily_expense.create", "daily_expense", ref.id, null, record); return NextResponse.json({ expenseId: ref.id }, { status: 201 }); } catch (error) { return apiError(error); } }
