import { FieldValue } from "@google-cloud/firestore";
import { NextResponse } from "next/server";
import { verifyInventoryAccess } from "@/lib/firebase-admin";
import { firestoreClient } from "@/lib/firestore";
import { apiError, jsonBody } from "@/lib/inventory/api";
import { demandPlanSchema } from "@/lib/inventory/domain";
import { serialize, writeAudit } from "@/lib/inventory/service";
export async function GET(request: Request) { try { const actor = await verifyInventoryAccess(request, ["admin", "planning_manager", "procurement_manager", "warehouse_manager", "kitchen_manager"]); const snapshot = await firestoreClient().collection("demand_plans").orderBy("created_at", "desc").limit(200).get(); return NextResponse.json({ demandPlans: snapshot.docs.map(serialize).filter((plan) => actor.isAdmin || actor.locationIds.includes(String(plan.location_id))) }); } catch (error) { return apiError(error); } }
export async function POST(request: Request) { try { const body = await jsonBody(request); const parsed = demandPlanSchema.parse(body); const actor = await verifyInventoryAccess(request, ["admin", "planning_manager"], parsed.locationId); const ref = parsed.planId ? firestoreClient().collection("demand_plans").doc(parsed.planId) : firestoreClient().collection("demand_plans").doc(); const record = { plan_id: ref.id, location_id: parsed.locationId, planning_period: { start_date: parsed.planningPeriod.startDate, end_date: parsed.planningPeriod.endDate }, period_consumer_count: parsed.periodConsumerCount, sub_period_consumer_count: parsed.subPeriodConsumerCount, service_days: parsed.serviceDays, sub_period_service_days: parsed.subPeriodServiceDays, servings_per_consumer_per_day: parsed.servingsPerConsumerPerDay, menu_type: parsed.menuType, status: parsed.status, created_by: actor.uid, approved_by: null, created_at: FieldValue.serverTimestamp(), updated_at: FieldValue.serverTimestamp() }; await ref.create(record); await writeAudit(actor.uid, "demand_plan.create", "demand_plan", ref.id, null, record); return NextResponse.json({ planId: ref.id }, { status: 201 }); } catch (error) { return apiError(error); } }
