import { FieldValue, Timestamp } from "@google-cloud/firestore";
import { NextResponse } from "next/server";
import { verifyStaffRole, ParentAuthError } from "@/lib/firebase-admin";
import { firestoreClient } from "@/lib/firestore";
import { franchiseApplicationStatuses, toFranchiseApplication, type FranchiseApplicationStatus } from "@/lib/franchise-applications";
import { writeAuditLog } from "@/lib/hardening";

const collection = "franchise_applications";
function failure(error: unknown) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to manage franchise applications." }, { status: error instanceof ParentAuthError ? 403 : 500 }); }
export async function GET(request: Request) { try { await verifyStaffRole(request, "admin"); const url = new URL(request.url); const snapshot = await firestoreClient().collection(collection).orderBy("created_at", "desc").limit(250).get(); let applications = snapshot.docs.map((item) => toFranchiseApplication(item.id, item.data())); const status = (url.searchParams.get("status") || "").toUpperCase(); const query = (url.searchParams.get("q") || "").trim().toLowerCase(); if (franchiseApplicationStatuses.includes(status as FranchiseApplicationStatus)) applications = applications.filter((item) => item.status === status); if (query) applications = applications.filter((item) => `${item.referenceId} ${item.applicantName} ${item.phone} ${item.email} ${item.selectedCity}`.toLowerCase().includes(query)); return NextResponse.json({ applications }, { headers: { "Cache-Control": "private, no-store" } }); } catch (error) { return failure(error); } }
export async function PUT(request: Request) { try { const staff = await verifyStaffRole(request, "admin"); const body = await request.json() as Record<string, unknown>; const referenceId = typeof body.referenceId === "string" ? body.referenceId.trim().toUpperCase() : ""; const status = typeof body.status === "string" ? body.status.toUpperCase() as FranchiseApplicationStatus : "RECEIVED"; const notes = typeof body.notes === "string" ? body.notes.trim().slice(0, 2000) : ""; const assignedTo = typeof body.assignedTo === "string" ? body.assignedTo.trim().slice(0, 120) : ""; if (!/^FR-[A-Z0-9]{8,24}$/.test(referenceId) || !franchiseApplicationStatuses.includes(status)) return NextResponse.json({ error: "Choose a valid franchise application and status." }, { status: 400 }); const reference = firestoreClient().collection(collection).doc(referenceId); if (!(await reference.get()).exists) return NextResponse.json({ error: "Application not found." }, { status: 404 }); await reference.set({ status, notes: notes || null, assigned_to: assignedTo || null, updated_at: FieldValue.serverTimestamp(), updated_by: staff.uid, workflow_history: FieldValue.arrayUnion({ status, changed_by: staff.uid, changed_at: Timestamp.now() }) }, { merge: true }); await writeAuditLog(staff.uid, "franchise_application.update", "franchise_application", referenceId, { status, assignedTo, hasNotes: Boolean(notes) }); return NextResponse.json({ updated: true, referenceId, status }); } catch (error) { return failure(error); } }
