import Link from "next/link";
import FranchisePaymentLink from "@/components/FranchisePaymentLink";
import { firestoreClient } from "@/lib/firestore";
import { toFranchiseApplication, type FranchiseApplication } from "@/lib/franchise-applications";
import { APPLICATION_FEE_INR, FRANCHISE_TOTAL_INVESTMENT_INR } from "@/lib/franchiseFees";
type Props = { searchParams: Promise<{ applicationId?: string }> };
async function load(referenceId: string): Promise<FranchiseApplication | null> { if (!/^FR-[A-F0-9]{8}$/.test(referenceId)) return null; try { const snapshot = await firestoreClient().collection("franchise_applications").doc(referenceId).get(); return snapshot.exists ? toFranchiseApplication(referenceId, snapshot.data() || {}) : null; } catch { return null; } }
export const dynamic = "force-dynamic";
export default async function FranchisePaymentPage({ searchParams }: Props) {
  const referenceId = ((await searchParams).applicationId || "").trim().toUpperCase(); const application = await load(referenceId); const paid = application?.paymentStatus === "PAID"; const approved = application?.status === "APPROVED_FOR_PAYMENT";
  return <main className="franchise-payment-page"><header className="topbar franchise-topbar"><Link className="brand" href="/"><span className="brand-mark">L</span><span>Lunch<span>Box</span></span></Link></header><section className="franchise-payment-card"><span className="payment-check">{paid ? "✓" : "⌛"}</span><span className="kicker">{paid ? "PAYMENT RECEIVED" : approved ? "APPROVED FOR PAYMENT" : "APPLICATION RECEIVED"}</span><h1>{paid ? "Your application fee has been verified." : approved ? "Your application is approved for payment." : "Your franchise application is under review."}</h1><p>{application ? <>Reference ID: <b>{application.referenceId}</b></> : "The application reference is invalid or unavailable."}</p>{application && <div className="payment-detail-grid"><article><small>Application status</small><b>{application.status.replaceAll("_", " ")}</b><p>{paid ? "Next step: agreement, franchise activation and onboarding." : approved ? "The territory review is complete." : "Our team is reviewing the applicant and territory."}</p></article><article><small>Application fee</small><b>{money(APPLICATION_FEE_INR)}</b><p>Collected only after approval. The indicative total investment is {money(FRANCHISE_TOTAL_INVESTMENT_INR)} and is not charged here.</p></article><article><small>Payment status</small><b>{application.paymentStatus.replaceAll("_", " ")}</b><p>Only the verified Razorpay webhook confirms payment.</p></article></div>}{approved && application && <FranchisePaymentLink applicationId={application.referenceId} />}{!approved && !paid && application && <p className="payment-note">No payment is due now. LunchBox must approve this application before authorizing payment.</p>}<Link className="franchise-return" href="/#franchises">Return to franchise territories</Link></section></main>;
}
function money(value: number) { return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value); }
