import { FieldValue } from "@google-cloud/firestore";
import { NextResponse } from "next/server";
import { z } from "zod";
import { verifyInventoryAccess } from "@/lib/firebase-admin";
import { firestoreClient } from "@/lib/firestore";
import { apiError, jsonBody } from "@/lib/inventory/api";
import { freightCost } from "@/lib/inventory/domain";
import { serialize, writeAudit } from "@/lib/inventory/service";
const schema=z.object({poId:z.string().min(2),rateId:z.string().min(2),originLocationId:z.string().min(2),destinationLocationId:z.string().min(2),chargeableUnits:z.number().nonnegative(),enteredCarrierFreightAmount:z.number().nonnegative().optional(),otherCharges:z.number().nonnegative().default(0),plannedDispatchDate:z.string().date(),expectedArrivalDate:z.string().date(),carrierReceiptNumber:z.string().max(120).nullish(),status:z.enum(["PLANNED","DISPATCHED","IN_TRANSIT","ARRIVED","CANCELLED"]).default("PLANNED")});
export async function GET(request:Request){try{const actor=await verifyInventoryAccess(request,["admin","logistics_manager","warehouse_manager","procurement_manager","finance_analyst"]);const s=await firestoreClient().collection("inbound_shipments").orderBy("created_at","desc").limit(300).get();return NextResponse.json({shipments:s.docs.map(serialize).filter((x)=>actor.isAdmin||actor.locationIds.includes(String(x.destination_location_id)))});}catch(e){return apiError(e)}}
export async function POST(request:Request){try{const parsed=schema.parse(await jsonBody(request));const actor=await verifyInventoryAccess(request,["admin","logistics_manager"],parsed.destinationLocationId);const db=firestoreClient();const rate=await db.collection("transportation_rate_master").doc(parsed.rateId).get();if(!rate.exists)throw new Error("Transport rate does not exist.");const estimated=freightCost({rateType:String(rate.get("rate_type")),chargeableUnits:parsed.chargeableUnits,routeDistanceKm:Number(rate.get("route_distance_km")),baseRate:Number(rate.get("base_rate")),minimumCharge:Number(rate.get("minimum_charge")),enteredCarrierFreightAmount:parsed.enteredCarrierFreightAmount,loadingCharge:Number(rate.get("loading_charge")),unloadingCharge:Number(rate.get("unloading_charge")),terminalCharge:Number(rate.get("terminal_charge")),handlingCharge:Number(rate.get("handling_charge")),insurancePercent:Number(rate.get("insurance_percent")),taxPercent:Number(rate.get("tax_percent")),otherCharges:parsed.otherCharges});const ref=db.collection("inbound_shipments").doc();const record={shipment_id:ref.id,po_id:parsed.poId,rate_id:parsed.rateId,mode:rate.get("mode"),origin_location_id:parsed.originLocationId,destination_location_id:parsed.destinationLocationId,route_distance_km:rate.get("route_distance_km"),chargeable_units:parsed.chargeableUnits,estimated_freight:estimated,actual_freight:null,carrier_receipt_number:parsed.carrierReceiptNumber||null,planned_dispatch_date:parsed.plannedDispatchDate,expected_arrival_date:parsed.expectedArrivalDate,status:parsed.status,created_by:actor.uid,created_at:FieldValue.serverTimestamp(),updated_at:FieldValue.serverTimestamp()};await ref.create(record);await writeAudit(actor.uid,"shipment.create","inbound_shipment",ref.id,null,record);return NextResponse.json({shipmentId:ref.id,estimatedFreight:estimated},{status:201});}catch(e){return apiError(e)}}
